/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TributariasRouteImport } from './routes/tributarias'
import { Route as ParafiscalesRouteImport } from './routes/parafiscales'
import { Route as LibrosRouteImport } from './routes/libros'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClienteRifRouteImport } from './routes/cliente.$rif'

const TributariasRoute = TributariasRouteImport.update({
  id: '/tributarias',
  path: '/tributarias',
  getParentRoute: () => rootRouteImport,
} as any)
const ParafiscalesRoute = ParafiscalesRouteImport.update({
  id: '/parafiscales',
  path: '/parafiscales',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrosRoute = LibrosRouteImport.update({
  id: '/libros',
  path: '/libros',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRifRoute = ClienteRifRouteImport.update({
  id: '/cliente/$rif',
  path: '/cliente/$rif',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/libros': typeof LibrosRoute
  '/parafiscales': typeof ParafiscalesRoute
  '/tributarias': typeof TributariasRoute
  '/cliente/$rif': typeof ClienteRifRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/libros': typeof LibrosRoute
  '/parafiscales': typeof ParafiscalesRoute
  '/tributarias': typeof TributariasRoute
  '/cliente/$rif': typeof ClienteRifRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/libros': typeof LibrosRoute
  '/parafiscales': typeof ParafiscalesRoute
  '/tributarias': typeof TributariasRoute
  '/cliente/$rif': typeof ClienteRifRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/libros' | '/parafiscales' | '/tributarias' | '/cliente/$rif'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/libros' | '/parafiscales' | '/tributarias' | '/cliente/$rif'
  id:
    | '__root__'
    | '/'
    | '/libros'
    | '/parafiscales'
    | '/tributarias'
    | '/cliente/$rif'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibrosRoute: typeof LibrosRoute
  ParafiscalesRoute: typeof ParafiscalesRoute
  TributariasRoute: typeof TributariasRoute
  ClienteRifRoute: typeof ClienteRifRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tributarias': {
      id: '/tributarias'
      path: '/tributarias'
      fullPath: '/tributarias'
      preLoaderRoute: typeof TributariasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parafiscales': {
      id: '/parafiscales'
      path: '/parafiscales'
      fullPath: '/parafiscales'
      preLoaderRoute: typeof ParafiscalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libros': {
      id: '/libros'
      path: '/libros'
      fullPath: '/libros'
      preLoaderRoute: typeof LibrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/$rif': {
      id: '/cliente/$rif'
      path: '/cliente/$rif'
      fullPath: '/cliente/$rif'
      preLoaderRoute: typeof ClienteRifRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibrosRoute: LibrosRoute,
  ParafiscalesRoute: ParafiscalesRoute,
  TributariasRoute: TributariasRoute,
  ClienteRifRoute: ClienteRifRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
