/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VencidasRouteImport } from './routes/vencidas'
import { Route as TributariasRouteImport } from './routes/tributarias'
import { Route as PendientesRouteImport } from './routes/pendientes'
import { Route as ParafiscalesRouteImport } from './routes/parafiscales'
import { Route as LibrosRouteImport } from './routes/libros'
import { Route as DeclaracionesaldiaRouteImport } from './routes/declaracionesaldia'
import { Route as ClientesvencidosRouteImport } from './routes/clientesvencidos'
import { Route as ClientespendientesRouteImport } from './routes/clientespendientes'
import { Route as ClientesaldiaRouteImport } from './routes/clientesaldia'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClienteRifRouteImport } from './routes/cliente.$rif'

const VencidasRoute = VencidasRouteImport.update({
  id: '/vencidas',
  path: '/vencidas',
  getParentRoute: () => rootRouteImport,
} as any)
const TributariasRoute = TributariasRouteImport.update({
  id: '/tributarias',
  path: '/tributarias',
  getParentRoute: () => rootRouteImport,
} as any)
const PendientesRoute = PendientesRouteImport.update({
  id: '/pendientes',
  path: '/pendientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ParafiscalesRoute = ParafiscalesRouteImport.update({
  id: '/parafiscales',
  path: '/parafiscales',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrosRoute = LibrosRouteImport.update({
  id: '/libros',
  path: '/libros',
  getParentRoute: () => rootRouteImport,
} as any)
const DeclaracionesaldiaRoute = DeclaracionesaldiaRouteImport.update({
  id: '/declaracionesaldia',
  path: '/declaracionesaldia',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesvencidosRoute = ClientesvencidosRouteImport.update({
  id: '/clientesvencidos',
  path: '/clientesvencidos',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientespendientesRoute = ClientespendientesRouteImport.update({
  id: '/clientespendientes',
  path: '/clientespendientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesaldiaRoute = ClientesaldiaRouteImport.update({
  id: '/clientesaldia',
  path: '/clientesaldia',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRifRoute = ClienteRifRouteImport.update({
  id: '/cliente/$rif',
  path: '/cliente/$rif',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/clientesaldia': typeof ClientesaldiaRoute
  '/clientespendientes': typeof ClientespendientesRoute
  '/clientesvencidos': typeof ClientesvencidosRoute
  '/declaracionesaldia': typeof DeclaracionesaldiaRoute
  '/libros': typeof LibrosRoute
  '/parafiscales': typeof ParafiscalesRoute
  '/pendientes': typeof PendientesRoute
  '/tributarias': typeof TributariasRoute
  '/vencidas': typeof VencidasRoute
  '/cliente/$rif': typeof ClienteRifRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/clientesaldia': typeof ClientesaldiaRoute
  '/clientespendientes': typeof ClientespendientesRoute
  '/clientesvencidos': typeof ClientesvencidosRoute
  '/declaracionesaldia': typeof DeclaracionesaldiaRoute
  '/libros': typeof LibrosRoute
  '/parafiscales': typeof ParafiscalesRoute
  '/pendientes': typeof PendientesRoute
  '/tributarias': typeof TributariasRoute
  '/vencidas': typeof VencidasRoute
  '/cliente/$rif': typeof ClienteRifRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/clientesaldia': typeof ClientesaldiaRoute
  '/clientespendientes': typeof ClientespendientesRoute
  '/clientesvencidos': typeof ClientesvencidosRoute
  '/declaracionesaldia': typeof DeclaracionesaldiaRoute
  '/libros': typeof LibrosRoute
  '/parafiscales': typeof ParafiscalesRoute
  '/pendientes': typeof PendientesRoute
  '/tributarias': typeof TributariasRoute
  '/vencidas': typeof VencidasRoute
  '/cliente/$rif': typeof ClienteRifRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/clientesaldia'
    | '/clientespendientes'
    | '/clientesvencidos'
    | '/declaracionesaldia'
    | '/libros'
    | '/parafiscales'
    | '/pendientes'
    | '/tributarias'
    | '/vencidas'
    | '/cliente/$rif'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/clientesaldia'
    | '/clientespendientes'
    | '/clientesvencidos'
    | '/declaracionesaldia'
    | '/libros'
    | '/parafiscales'
    | '/pendientes'
    | '/tributarias'
    | '/vencidas'
    | '/cliente/$rif'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/clientesaldia'
    | '/clientespendientes'
    | '/clientesvencidos'
    | '/declaracionesaldia'
    | '/libros'
    | '/parafiscales'
    | '/pendientes'
    | '/tributarias'
    | '/vencidas'
    | '/cliente/$rif'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRoute
  ClientesaldiaRoute: typeof ClientesaldiaRoute
  ClientespendientesRoute: typeof ClientespendientesRoute
  ClientesvencidosRoute: typeof ClientesvencidosRoute
  DeclaracionesaldiaRoute: typeof DeclaracionesaldiaRoute
  LibrosRoute: typeof LibrosRoute
  ParafiscalesRoute: typeof ParafiscalesRoute
  PendientesRoute: typeof PendientesRoute
  TributariasRoute: typeof TributariasRoute
  VencidasRoute: typeof VencidasRoute
  ClienteRifRoute: typeof ClienteRifRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vencidas': {
      id: '/vencidas'
      path: '/vencidas'
      fullPath: '/vencidas'
      preLoaderRoute: typeof VencidasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tributarias': {
      id: '/tributarias'
      path: '/tributarias'
      fullPath: '/tributarias'
      preLoaderRoute: typeof TributariasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pendientes': {
      id: '/pendientes'
      path: '/pendientes'
      fullPath: '/pendientes'
      preLoaderRoute: typeof PendientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parafiscales': {
      id: '/parafiscales'
      path: '/parafiscales'
      fullPath: '/parafiscales'
      preLoaderRoute: typeof ParafiscalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libros': {
      id: '/libros'
      path: '/libros'
      fullPath: '/libros'
      preLoaderRoute: typeof LibrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/declaracionesaldia': {
      id: '/declaracionesaldia'
      path: '/declaracionesaldia'
      fullPath: '/declaracionesaldia'
      preLoaderRoute: typeof DeclaracionesaldiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientesvencidos': {
      id: '/clientesvencidos'
      path: '/clientesvencidos'
      fullPath: '/clientesvencidos'
      preLoaderRoute: typeof ClientesvencidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientespendientes': {
      id: '/clientespendientes'
      path: '/clientespendientes'
      fullPath: '/clientespendientes'
      preLoaderRoute: typeof ClientespendientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientesaldia': {
      id: '/clientesaldia'
      path: '/clientesaldia'
      fullPath: '/clientesaldia'
      preLoaderRoute: typeof ClientesaldiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/$rif': {
      id: '/cliente/$rif'
      path: '/cliente/$rif'
      fullPath: '/cliente/$rif'
      preLoaderRoute: typeof ClienteRifRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRoute,
  ClientesaldiaRoute: ClientesaldiaRoute,
  ClientespendientesRoute: ClientespendientesRoute,
  ClientesvencidosRoute: ClientesvencidosRoute,
  DeclaracionesaldiaRoute: DeclaracionesaldiaRoute,
  LibrosRoute: LibrosRoute,
  ParafiscalesRoute: ParafiscalesRoute,
  PendientesRoute: PendientesRoute,
  TributariasRoute: TributariasRoute,
  VencidasRoute: VencidasRoute,
  ClienteRifRoute: ClienteRifRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
